alias artserve='php artisan serve --port=8081'
alias clearlog='echo ''> storage/logs/laravel.json.log'
alias func='vi ~/git/bash-profiles/.bash_functions'
alias gitclean='git branch --merged | grep -v "\*\|master\|develop" | xargs -n 1 git branch -d'
alias int='cd ~/git/integration'
alias ionserve='ionic serve --lab'
alias ll='ls -alGFh'
alias mysql='mysql -uroot -h 127.0.0.1'
alias mysqlstart="/usr/local/opt/mysql/bin/mysql.server start"
alias routecnt='php artisan route:list --path=t/api/entities |echo $(wc -l) -4 | bc'
alias sphp54='brew unlink php56; brew link php54; sudo apachectl restart'
alias social='cd ~/git/social-media-service'
alias sphp56='brew unlink php54; brew link php56; sudo apachectl restart'
alias srcbash='source ~/.bashrc'
alias chefupdate='cd /home/rjarnutowski/git/python_chef_updater'
